export const featuredData = [
  {
    id: 1,
    image: "/images/iosDeveloper.png",
    name: "Company XY. Full-time",
    title: "Senior iOS Developer",
    description: "in the spotlight",
    city: "New York",
    site: "Remote",
  },
  { id: 2,
    image: "/CompanyLogo.png",
    name: "Company MN. Full-time",
    title: "AI/ML Engineer",
    description: "in the spotlight",
    city: "New York",
    site: "Remote",
  },
  {
    id: 3,
    image: "/images/react.png",
    name: "Company RM. Full-time",
    title: "Senior iOS Developer",
    description: "in the spotlight",
    city: "New York",
    site: "Remote",
  },
  {
    id: 4,
    image: "/images/Andriod.png",
    name: "Company XY. Full-time",
    title: "Senior iOS Developer",
    description: "in the spotlight",
    city: "New York",
    site: "Remote",
  },
  {
    id: 5,
    image: "/images/flutter.png",
    name: "Company XY. Full-time",
    title: "Senior iOS Developer",
    description: "in the spotlight",
    city: "New York",
    site: "Remote",
  },
  {
    id: 6,
    image: "/images/netApplication.png",
    name: "Company XY. Full-time",
    title: "Senior iOS Developer",
    description: "in the spotlight",
    city: "New York",
    site: "Remote",
  },
];