export const RecentJobData = [
  {
    id: 1,
    image: "/images/reactNativ.png",
    name: "Company AQ. Part-time",
    title: "React Native Mobile Developer",
    date: "Sep 14, 2024",
    city: "Palo Alto, CA",
    site: "Remote",
  },
  {
    id: 2,
    image: "/images/python.jpeg",
    name: "Company PD. Part-time",
    title: "Python Developer",
    date: "Sep 13, 2024",
    city: "London, Uk",
    site: "Remote",
  },
  {
    id: 3,
    image: "/images/SeniorJavascript.png",
    name: "Company LK. Full-time",
    title: "Senior JavaScript Developer",
    date: "Sep 13, 2024",
    city: "Atlanta, USA",
    site: "Remote",
  },
  {
    id: 4,
    image: "/images/PHPDeveloper.png",
    name: "Company RT. InternShip",
    title: "PHP Developer",
    date: "Sep 12, 2024",
    city: "Amsterdarn, NL",
    site: "Remote",
  },
  {
    id: 5,
    image: "/images/reactNativ.png",
    name: "Company IU. Part-time",
    title: "Senior web Developer",
    date: "Sep 11, 2024",
    city: "Berlin, GER",
    site: "Remote",
  },
  {
    id: 6,
    image: "/images/java.png",
    name: "Company OB. Full-time",
    title: "Java Developer",
    date: "Sep 10, 2024",
    city: "Seatle, USA",
    site: "Remote",
  },
  {
    id: 7,
    image: "/images/C++.png",
    name: "Company SS. Freelencer",
    title: "Software Engineer (C++)",
    date: "Sep 9, 2024",
    city: "Denver, USA",
    site: "Remote",
  },
  {
    id: 8,
    image: "/images/SwiftUI.png",
    name: "Company KW. Full-time",
    title: "Swift UI Developer (iOS, macOS, watchOS)",
    date: "Sep 8, 2024",
    city: "San Fransciso, USA",
    site: "Remote",
  },
  {
    id: 9,
    image: "/images/RubyRails.png",
    name: "Company DS. Internship",
    title: "React Native Mobile Developer",
    date: "Sep 7, 2024",
    city: "Boston, USA",
    site: "Remote",
  },
  {
    id: 10,
    image: "/images/Typescript.png",
    name: "Company FF. Part-time",
    title: "AWS Full Stack Engineer (Node.js, TypeScript)",
    date: "Sep 6, 2024",
    city: "Madrid, SP",
    site: "Remote",
  },
  {
    id: 11,
    image: "/images/SQLPhython.jpeg",
    name: "Company FT. Freelancer",
    title: "Python + SQL Developer",
    date: "Sep 5, 2024",
    city: "Zurich, SZ",
    site: "Remote",
  },
  {
    id: 12,
    image: "/images/KMM.png",
    name: "Company CV. Part-time",
    title: "Kotlin Multiplatform Mobile (KMM) Developer",
    date: "Sep 14, 2024",
    city: "Palo Alto, CA",
    site: "Remote",
  },
];